spring:
  application:
    name: TPO_project_04
  h2:
    console:
      path: /my-console
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/library
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql