INSERT INTO publisher (name, address)
VALUES ('Penguin Books', 'London, UK'),
       ('HarperCollins', 'New York, USA'),
       ('Simon & Schuster', 'New York, USA'),
       ('Macmillan Publishers', 'London, UK'),
       ('Hachette Livre', 'Paris, France'),
       ('Scholastic', 'New York, USA'),
       ('Random House', 'New York, USA'),
       ('Pearson', 'London, UK'),
       ('Oxford University Press', 'Oxford, UK'),
       ('Cambridge University Press', 'Cambridge, UK'),
       ('Springer', 'Berlin, Germany'),
       ('Elsevier', 'Amsterdam, Netherlands'),
       ('Wiley', 'Hoboken, USA'),
       ('McGraw-Hill', 'New York, USA'),
       ('Thomson Reuters', 'Toronto, Canada'),
       ('Cengage', 'Boston, USA'),
       ('Taylor & Francis', 'Oxford, UK'),
       ('SAGE Publications', 'Thousand Oaks, USA'),
       ('Kogan Page', 'London, UK'),
       ('MIT Press', 'Cambridge, USA');

INSERT INTO author (first_name, last_name, bio)
VALUES ('John', 'Doe', 'Expert in AI'),
       ('Jane', 'Smith', 'Specialist in ML'),
       ('Alice', 'Johnson', 'Data Scientist'),
       ('Bob', 'Brown', 'Historian'),
       ('Carol', 'White', 'Mathematician'),
       ('Dave', 'Clark', 'Physicist'),
       ('Eve', 'Davis', 'Biologist'),
       ('Frank', 'Miller', 'Chemist'),
       ('Grace', 'Wilson', 'Philosopher'),
       ('Hank', 'Moore', 'Sociologist'),
       ('Ivy', 'Taylor', 'Economist'),
       ('Jack', 'Anderson', 'Psychologist'),
       ('Kathy', 'Thomas', 'Linguist'),
       ('Leo', 'Jackson', 'Political Scientist'),
       ('Mia', 'Martin', 'Educator'),
       ('Nick', 'Lee', 'Anthropologist'),
       ('Olivia', 'Perez', 'Artist'),
       ('Paul', 'Thompson', 'Musician'),
       ('Quinn', 'Harris', 'Theologian'),
       ('Rachel', 'Young', 'Engineer');

INSERT INTO book (title, publication_date, publisher_id)
VALUES ('AI for Beginners', '2020-01-01', 1),
       ('Advanced Machine Learning', '2020-05-15', 2),
       ('Data Science Essentials', '2021-03-10', 3),
       ('World History', '2019-11-20', 4),
       ('Mathematics Simplified', '2018-06-05', 5),
       ('The Quantum Realm', '2020-08-08', 6),
       ('Biology 101', '2022-02-02', 7),
       ('Organic Chemistry', '2021-07-07', 8),
       ('Philosophy of Mind', '2019-09-09', 9),
       ('Modern Sociology', '2020-12-12', 10),
       ('Economics Explained', '2017-04-04', 11),
       ('Introduction to Psychology', '2016-10-10', 12),
       ('Linguistics Today', '2018-02-02', 13),
       ('Political Systems', '2021-01-01', 14),
       ('Education in the 21st Century', '2021-06-06', 15),
       ('Cultural Anthropology', '2020-03-03', 16),
       ('The Art Book', '2022-05-05', 17),
       ('Music Theory', '2019-08-08', 18),
       ('Theology and Society', '2017-07-07', 19),
       ('Engineering Basics', '2018-09-09', 20);

INSERT INTO book_author (book_id, author_id)
VALUES (1, 1),
       (2, 2),
       (3, 3),
       (4, 4),
       (5, 5),
       (6, 6),
       (7, 7),
       (8, 8),
       (9, 9),
       (10, 10),
       (11, 11),
       (12, 12),
       (13, 13),
       (14, 14),
       (15, 15),
       (16, 16),
       (17, 17),
       (18, 18),
       (19, 19),
       (20, 20),
       (1, 2),
       (1, 3),
       (2, 4),
       (2, 5),
       (3, 6),
       (4, 7),
       (5, 8),
       (6, 9),
       (7, 10),
       (8, 11);
